### ISSUE TITLE
Are vectors necessary here?

### ISSUE THREAD

**Issue by justinmcgrath** [Hritik-Raj/Ouster-Lidar#1]
Only the current value in the loop is used for these vectors, and the vectors are never used again later. Are they necessary?

https://github.com/Hritik-Raj/Ouster-Lidar/blob/76f788cbdb378fdbe6f25a1e9467adc1733f3222/ouster_client/src/example.cpp#L107-L109

**Comment by Hritik-Raj** [comment]
You are right, the vectors aren't necessary, will change this right now

**Comment by Hritik-Raj** [comment]
This has been changed
